arr = ['hello', 'goodMonning', 'bye'];
arr[3] = 'Привет';
arr[arr.length] = 'Пока';
arr.push('все дома');
console.log(arr);
console.log(arr[0]);
arrObj = new Array(2,2);
arrObjstring = new Array('2');
arrObjO = new Array(2);
console.log(arrObj);
console.log(arrObjstring);
console.log(arrObjO);